# Generated by Django 3.2.9 on 2021-12-03 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='511897494388454', max_length=16)),
                ('cvv2', models.PositiveSmallIntegerField(default='569')),
                ('expiration_date', models.DateTimeField(blank=True, verbose_name='Card date and time')),
                ('balance', models.BigIntegerField(verbose_name='Card Balance')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_structure.client')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BigIntegerField(default=0, verbose_name='Transaction money value')),
                ('status', models.CharField(default='Неизвестная ошибка', max_length=15, verbose_name='Transaction status')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Transaction date and time')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_structure.creditcard', verbose_name='Money Receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_structure.client', verbose_name='Money Sender')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, verbose_name='Client Issue text')),
                ('answer', models.TextField(blank=True, verbose_name='Admin Answer text')),
                ('state', models.CharField(default='not_solved', max_length=15, verbose_name='Transaction status')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Question date and time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_structure.client', verbose_name='Question Author')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_structure.admin', verbose_name='Who answered question')),
            ],
        ),
    ]
