# Generated by Django 3.2.9 on 2021-12-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cvv2',
            field=models.PositiveSmallIntegerField(default='533'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.CharField(default='544426502898190', max_length=16),
        ),
    ]
