# Generated by Django 3.2.9 on 2021-12-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_structure', '0002_auto_20211203_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cvv2',
            field=models.PositiveSmallIntegerField(default='002'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.CharField(default='549835076923482', max_length=16),
        ),
    ]
