# Generated by Django 3.2.9 on 2021-12-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_structure', '0003_auto_20211203_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cvv2',
            field=models.PositiveSmallIntegerField(default='069'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.CharField(default='546667177433273', max_length=16),
        ),
    ]
