# Generated by Django 3.2.9 on 2021-12-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_structure', '0004_auto_20211205_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cvv2',
            field=models.PositiveSmallIntegerField(default='694'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.CharField(default='524500130725185', max_length=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Transaction date and time'),
        ),
    ]
