; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27045.0 

	TITLE	C:\Users\kolya\Documents\GitHub\onpu\2_year\Computer Arhitecture\8_variant\lab6_test\lab6_test\lab3_macr.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__396DCCC4_lab3_macr@cpp DB 01H
msvcjmc	ENDS
END
